### ISSUE TITLE
Add sources

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/blenchbenuecongo#1]
Sources are, according to comparalex:

* Williamson, Kay and Kiyoshi Shimizu (eds.). 1968. Benue-Congo Comparative Wordlist Volume I. Ibadan, Nigeria: West African Linguistic Society.
* Williamson, Kay (ed.). 1973. Benue-Congo Comparative Wordlist, Volume II. Ibadan, Nigeria: West African Linguistic Society. 

which are:
https://glottolog.org/resource/reference/id/84099
https://glottolog.org/resource/reference/id/64189

**Comment by chrzyki** [comment]
Done.
