### ISSUE TITLE
Map concept list to Concepticon

### ISSUE THREAD

**Issue by chrzyki** [lexibank/blenchbenuecongo#3]

**Comment by chrzyki** [comment]
See this PR: https://github.com/concepticon/concepticon-data/pull/926 Note that `NUMBER` in the mapped concept list can still be used for mapping lexemes; however, `TWO HUNDRED` is a separate concept in the final mapped list (so it has `NUMBER` 116 instead of `115.1`).

**Comment by LinguList** [comment]
Number is in fact a free form in concept lists, right? So I'd not give it 116, but retain 115.1 in this case, since this is the number given in the original?

**Comment by chrzyki** [comment]
In the original book publication it is the 116th item. Only ComparaLex lumped the two concepts together.

**Comment by LinguList** [comment]
Ah, okay, then this one item can be a hack in lexibank...

**Comment by chrzyki** [comment]
Okay. :) I'll prepare this dataset accordingly when Concepticon is ready with the list.

**Comment by chrzyki** [comment]
Done
